# .github/labels.yml
- name: status/blocked
  color: "d73a4a"
- name: status/in-progress
  color: "0075ca"
- name: status/review
  color: "7057ff"
- name: priority/critical
  color: "b60205"
- name: priority/high
  color: "d93f0b"
- name: priority/medium
  color: "fbca04"
- name: priority/low
  color: "0e8a16"
