# Generated by Django 5.1.7 on 2025-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="assigned_locations",
            field=models.ManyToManyField(to="common.location"),
        ),
    ]
