# Generated by Django 5.1.7 on 2025-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_employee_assigned_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
