# Generated by Django 5.1.7 on 2025-04-02 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_event_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'given_name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='card',
            name='designation',
            field=models.TextField(help_text='Unique identifier for the card (i.e., number printed on it).', unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, help_text='Locations this employee is typically associated with (informational).', to='common.location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='card_number',
            field=models.ForeignKey(blank=True, help_text='The access card currently assigned to the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.card'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The system user who recorded this event, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred.'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.TextField(help_text='The name describing the event type.', unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(help_text="Name of the location (e.g., 'Main Security', 'Repository and Conservation').", unique=True),
        ),
    ]
