# Generated by Django 5.2.1 on 2025-07-25 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_employee_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_departure_time',
            field=models.TimeField(blank=True, help_text="Employee's assigned departure time", null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_lunch_time',
            field=models.TimeField(blank=True, help_text="Employee's assigned lunch time", null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this employee is currently active'),
        ),
        migrations.AlterField(
            model_name='card',
            name='designation',
            field=models.CharField(help_text='Unique identifier for the card (i.e., number printed on it).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='given_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(help_text='The name describing the event type.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text="Name of the location (e.g., 'Main Security', 'Repository and Conservation').", max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lunch_time', models.TimeField(blank=True, help_text='Time employee took lunch', null=True)),
                ('left_lunch_on_time', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('APPOINTMENT', 'Appointment')], help_text='Did employee leave for lunch at assigned time?', max_length=11, null=True)),
                ('returned_on_time_after_lunch', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('APPOINTMENT', 'Appointment')], help_text='Did employee return to workstation on time after lunch?', max_length=11, null=True)),
                ('returned_after_lunch', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('APPOINTMENT', 'Appointment')], help_text='Did employee return after lunch?', max_length=11, null=True)),
                ('standup_attendance', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('APPOINTMENT', 'Appointment')], help_text='Did employee attend stand-up meeting?', max_length=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft - In Progress'), ('PARTIAL', 'Partial - Some data entered'), ('COMPLETE', 'Complete - All data entered'), ('REVIEWED', 'Reviewed - Supervisor approved')], default='DRAFT', help_text='Current status of this attendance record', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='common.employee')),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='Last user who updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'employee__surname', 'employee__given_name'],
                'indexes': [models.Index(fields=['date'], name='common_atte_date_52ce32_idx'), models.Index(fields=['employee', 'date'], name='common_atte_employe_b000c2_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
