# Generated by Django 5.2.1 on 2025-07-27 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_employee_assigned_departure_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status', 'date'], name='common_atte_status_3ab533_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'status'], name='common_atte_employe_6a8451_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active', 'surname', 'given_name'], name='common_empl_is_acti_6655d7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['card_number', 'is_active'], name='common_empl_card_nu_fec38e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['employee', '-timestamp'], name='idx_emp_events_emp_time'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'timestamp'], name='idx_event_type_time'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location', 'timestamp'], name='idx_location_time'),
        ),
    ]
