# Generated by Django 4.2.1 on 2025-07-30 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0010_attendancerecord_common_atte_status_3ab533_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('security', 'Security'), ('attendance', 'Attendance Management'), ('reporting', 'Reporting'), ('admin', 'Administrator')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='common_atte_date_52ce32_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='common_atte_status_3ab533_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='common_atte_employe_6a8451_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='idx_emp_events_emp_time',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='common_even_event_t_8450f4_idx',
            old_name='idx_event_type_time',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='common_even_locatio_2b06f4_idx',
            old_name='idx_location_time',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='common_atte_date_c50248_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['created_by', 'created_at'], name='common_atte_created_a3c118_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['employee', 'timestamp'], name='common_even_employe_95da27_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', 'timestamp'], name='common_even_created_5521aa_idx'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
