# Generated by Django 4.2.23 on 2025-08-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_add_location_timestamps'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'employee'], name='common_atte_date_ab874b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status', 'date'], name='common_atte_status_3ab533_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active', 'name'], name='common_depa_is_acti_fd4f41_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code', 'is_active'], name='common_depa_code_e4d0be_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'is_active'], name='common_empl_departm_489820_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp', 'event_type'], name='common_even_timesta_5bdea1_idx'),
        ),
    ]
