# Generated by Django 4.2.23 on 2025-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticscache',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='User ID for user-specific cache entries', null=True),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='user_specific',
            field=models.BooleanField(default=False, help_text='Whether this cache entry is user-specific'),
        ),
        migrations.AlterField(
            model_name='analyticscache',
            name='cache_type',
            field=models.CharField(choices=[('daily_summary', 'Daily Summary'), ('employee_analytics', 'Employee Analytics'), ('department_analytics', 'Department Analytics'), ('attendance_heatmap', 'Attendance Heatmap'), ('movement_patterns', 'Movement Patterns'), ('anomaly_detection', 'Anomaly Detection'), ('department_stats', 'Department Statistics'), ('employee_status', 'Employee Status'), ('system_performance', 'System Performance'), ('comprehensive_report', 'Comprehensive Report')], help_text='Type of cached analytics data', max_length=50),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['user_specific', 'user_id'], name='common_anal_user_sp_ff0510_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['cache_key', 'expires_at'], name='common_anal_cache_k_5281b1_idx'),
        ),
    ]
