# .github/ISSUE_TEMPLATE/bug_report.yml
name: Bug Report
description: Report an issue or problem
title: "[BUG] "
labels: ["bug"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Frontend
        - Backend
        - ROI Selector
        - Infrastructure
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Development
        - Staging
        - Production
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Impact Level
      options:
        - Critical (System Down)
        - Major (Feature Broken)
        - Minor (Inconvenience)
    validations:
      required: true
  - type: input
    id: browser-os
    attributes:
      label: Browser/OS
      placeholder: e.g., Chrome 96/MacOS 12.1
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should happen?
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Screenshots
      placeholder: Include any relevant logs or screenshots
  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      placeholder: e.g., #123, #456
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., commit hash or environment
