# .github/ISSUE_TEMPLATE/technical_task.yml
name: Technical Task
description: Internal development task
title: "[TASK] "
labels: ["task"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Frontend
        - Backend
        - ROI Selector
        - Infrastructure
        - Documentation
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Task Description
      placeholder: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      placeholder: |
        - Implementation details
        - Required dependencies
        - API endpoints affected
  - type: textarea
    id: dependencies
    attributes:
      label: Task Dependencies
      placeholder: List any prerequisite tasks or blockers
  - type: textarea
    id: testing-requirements
    attributes:
      label: Testing Requirements
      placeholder: |
        - Unit tests
        - Integration tests
        - Manual testing steps
  - type: textarea
    id: risk-assessment
    attributes:
      label: Risk Assessment
      placeholder: Potential risks and mitigation strategies
  - type: textarea
    id: migration-steps
    attributes:
      label: Migration Steps
      placeholder: Required database or infrastructure migrations
  - type: checkboxes
    id: requirements
    attributes:
      label: Additional Requirements
      options:
        - label: Documentation updates required
        - label: Database changes required
        - label: API changes required
        - label: UI changes required
  - type: dropdown
    id: effort
    attributes:
      label: Effort Estimation
      options:
        - XS (1-2 days)
        - S (3-5 days)
        - M (1-2 weeks)
        - L (2-4 weeks)
        - XL (4+ weeks)
