# Generated by Django 4.2.20 on 2025-03-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_event_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='card_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.card'),
        ),
    ]
