name: Tests # Name of the workflow
on:     
  push:
    branches: [ main ]     # Runs on pushes to these branches 
  pull_request:
    branches: [ main ]     # Runs on pull requests from these branhces
jobs:                                   # Jobs
  jest-test:                                 # Name of the Job
    timeout-minutes: 60                 # Will kill the job if it excceds this amount of time     
    runs-on: [self-hosted, Linux, x64]  # Tags for which runner the job will run on
    steps:                              #
      - uses: actions/checkout@v4       # Checkout the repo
      - uses: actions/setup-node@v4     # Sets up node enviornment
        with:
          node-version: 20              # Explicitly uses Node 20

      - name: Cache node modules        # Step to cache node module dependacies between test runs. 
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies     # Installs dependancies
        run: npm install -g pnpm && pnpm install    
      - name: Run Jest
        run: npm test                  # Runs test
  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20              # Explicitly uses Node 20

      - name: Cache node modules        # Step to cache node module dependacies between test runs. 
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies     # Installs dependancies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

